### PR TITLE
Update to 1.9.3 Public Official

### PR DESCRIPTION
**Pull request by hadess**
The sysdeps patch is replaced with upstream cmake options to disable the internal deps, with only the OCCT docs patch being split off.

### CODE REVIEW

**Comment by hadess** [comment]
bot, build

**Comment by MackBambu** [comment]
0001-deps-Cereal-Update-Cereal-to-fix-build-error.patch

**Comment by MackBambu** [comment]
glfw-Don-t-crash-on-calls-to-focus-or-icon.patch

**Comment by hadess** [comment]
> 0001-deps-Cereal-Update-Cereal-to-fix-build-error.patch
> This patch can be removed
> [bambulab/BambuStudio@c837829](https://github.com/bambulab/BambuStudio/commit/c8378296fa42836408dceb877452b7d4aa32c1f6)

I would have much preferred you to update https://github.com/flathub/com.bambulab.BambuStudio/pull/25 before the release, that would have allowed me to cherry-pick those changes in this update, instead of having to reverse engineer the upstream changes.

> glfw-Don-t-crash-on-calls-to-focus-or-icon.patch

What about it? There were no changes to glfw in the Flatpak manifest (which ships 3.3.9), or in BambuStudio's deps (which builds an older 3.3.7).

**Comment by MackBambu** [comment]
> I would have much preferred you to update #25 before the release, that would have allowed me to cherry-pick those changes in this update, instead of having to reverse engineer the upstream changes.

Sorry, i was going to sort this PR next Monday.
Everything looks good now, except wxwidgets still has patches, but I respect that.

> What about it? There were no changes to glfw in the Flatpak manifest (which ships 3.3.9), or in BambuStudio's deps (which builds an older 3.3.7).

I wasn't able to add this patch because of errors compiling on windows and macs

**Pull request merged**
